import "../globals.css";
import "../../public/static/vendor/fontawesome-free/css/all.css";
import 'react-spinner-animated/dist/index.css'
import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import Sidebar from "../components/Sidebar";
import NavBar from "../components/NavBar";
import FooterBar from "../components/FooterBar";
import Head from "next/head";
import Script from "next/script";
import ImportBsj from "../components/ImportBsj";
import Providers from "../Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,newModal
}: {
  children: React.ReactNode;
  newModal: React.ReactNode;
}) {
  return (<html>
    <body id="page-top">
      <Providers>
      {/* <!-- Page Wrapper --> */}
      <div id="wrapper">
        {/* <!-- Sidebar --> */}
        <Sidebar />

        {/* <!-- End of Sidebar --> */}

        {/* <!-- Content Wrapper --> */}
        <div id="content-wrapper" className="d-flex flex-column">
          {/* <!-- Main Content --> */}
          <div id="content">
            {/* <!-- Topbar --> */}
            
            <NavBar />
            {/* <!-- End of Topbar --> */}

            {/* <!-- Begin Page Content --> */}
            <div className="container-fluid">

              {children}

              {/* <!-- Page Heading --> */}
            </div>
            {/* <!-- /.container-fluid --> */}
          </div>
          {/* <!-- End of Main Content --> */}

          {/* <!-- Footer --> */}
          <FooterBar />
          {/* <!-- End of Footer --> */}
        </div>
        {/* <!-- End of Content Wrapper --> */}
      </div>
      {/* <!-- End of Page Wrapper --> */}

      {/* <!-- Scroll to Top Button--> */}
      <a className="scroll-to-top rounded" href="#page-top">
        <i className="fas fa-angle-up"></i>
      </a>

      </Providers>
    </body>
    </html>
  );
}
